### PR TITLE
Use hash instead of nonce for redirect to payment confirmation

### LINKED ISSUE #52: Use payment key instead of nonce for confirmation redirect
In support ticket https://freescout.pronamic.nl/conversation/4094 we discovered that a nonce being used for safe redirection to a Gravity Forms confirmation message for a payment, doesn't work as expected for logged in users with the https://github.com/pronamic/wp-pronamic-pay-ingenico gateway integration.

https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/06b56397281b31119efaec67ccb837b50133c4f3/src/Extension.php#L513-L542

The issue is that the PSP requests the payment return URL in the background. This requests results in a redirect to the payment return redirect URL with a nonce for an anonymous visitor. The PSP redirects to this redirect URL, instead of the originally provided payment return URL. The nonce is invalid for the logged in user, resulting in the payment confirmation not being shown.

To be clear, I can see these fields being submitted to the PSP on payment start:

```html
	<input type="hidden" name="ACCEPTURL" value="https://www.example.com/?payment=40749&amp;key=pay_68401e6d5ff46&amp;status=accept">
	<input type="hidden" name="CANCELURL" value="https://www.example.com/?payment=40749&amp;key=pay_68401e6d5ff46&amp;status=cancel">
	<input type="hidden" name="DECLINEURL" value="https://www.example.com/?payment=40749&amp;key=pay_68401e6d5ff46&amp;status=decline">
	<input type="hidden" name="EXCEPTIONURL" value="https://www.example.com/?payment=40749&amp;key=pay_68401e6d5ff46&amp;status=exception">
```

None of these URL's refer to the payment return redirect URL, but I noticed a URL like `https://www.example.com/page/?pay_confirmation={payment_id}&_wpnonce={nonce}#gf_4` being used for redirection by the PSP (in the HTML source of the redirect message). As a temporary solution, I've suggested unchecking the setting **Configuratie → Technische instellingen → Tab 'Transactiefeedback' → Section 'eCommerce' → Uncheck 'Ik wil dat Worldline een kort redirectiebericht toont aan de klant voordat deze wordt teruggestuurd naar mijn website'** in the PSP dashboard — which will probably resolve this.

Image

To resolve the issue, I was thinking we could as well use the unique payment key instead of a nonce. What do you think, @remcotolsma?

### PR DESCRIPTION
**Pull request by rvdsteege**
Fix #52.

### CODE REVIEW

File: src/Extension.php [hunk 1]
```diff
@@ -1077,16 +1077,16 @@ public function maybe_display_confirmation() {
 			return;
 		}
 
-		// Verify nonce.
-		if ( ! \array_key_exists( '_wpnonce', $_GET ) ) {
+		// Verify hash.
+		if ( ! filter_has_var( INPUT_GET, 'hash' ) ) {
```
Comment (remcotolsma) [inline src/Extension.php:1081]: Don't use `filter_has_var`?
https://github.com/search?q=repo%3AWordPress%2FWordPress%20filter_has_var&type=code

File: src/Extension.php [hunk 2]
```diff
@@ -1077,16 +1077,16 @@ public function maybe_display_confirmation() {
...
 			return;
 		}
 
-		$nonce = \sanitize_text_field( \wp_unslash( $_GET['_wpnonce'] ) );
+		$hash = \sanitize_text_field( \wp_unslash( filter_input( INPUT_GET, 'hash' ) ) );
```
Comment (remcotolsma) [inline src/Extension.php:1085]: Don't use `filter_input`?
https://github.com/search?q=repo%3AWordPress%2FWordPress+filter_input&type=code

**Review by remcotolsma — CHANGES_REQUESTED** [review]
